serverConfig:
  tickRate: 100
  whitelist:
    - YoshiUnfriendly
  gclToCPU: true
  maxCPU: 100
  baseCPU: 20
  stepCPU: 10

mods:
  - screepsmod-auth
  - screepsmod-admin-utils
  - screepsmod-mongo
bots:
  simplebot: screepsbot-zeswarm

launcherOptions:
  # If set, automatically ensures all mods are updated
  autoUpdate: false
  # If set, forward console messages to terminal
  logConsole: false
